---
# Taken from https://ssl-config.mozilla.org/#server=apache&version=2.4.6&config=intermediate&openssl=1.0.2&guideline=5.6
apache::mod::ssl::ssl_cipher: 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
apache::mod::ssl::ssl_protocol:
  - 'ALL'
  - '-SSLv3'
  - '-TLSv1'
  - '-TLSv1.1'
apache::trace_enable: 'Off'
