sudo: false
language: ruby
addons:
  apt:
    packages:
    - asciidoc
    - libxml2-utils
    - xsltproc
    - docbook-xsl
    - ca-certificates
rvm: 2.4
env:
  - PUPPET_VERSION=5.0
script:
  #
  # Run rspec tests on migrations
  #
  - bundle exec rake spec
  #
  # Test basic installer configuration works
  #
  - INSTDIR=$(mktemp -d)
  - bundle exec rake build install PREFIX=$INSTDIR
  - bundle exec $INSTDIR/sbin/foreman-installer --help --scenario foreman
  - bundle exec $INSTDIR/sbin/foreman-installer --help --scenario foreman-proxy-content
  - bundle exec $INSTDIR/sbin/foreman-installer --help --scenario katello
  - bundle exec $INSTDIR/sbin/foreman-proxy-certs-generate --help
  #
  # Test separate build/installation steps with different prefixes
  # No references to INSTDIR should be present when built with PREFIX=/
  #
  - bundle exec rake clean build PREFIX=/ SYSCONFDIR=/etc
  - INSTDIR=$(mktemp -d)
  - bundle exec rake install PREFIX=$INSTDIR
  - "! find $INSTDIR -type f | xargs grep $INSTDIR"
  - "! find $INSTDIR -type l -printf '%P: ' -exec readlink {} \\; | grep $INSTDIR"
