---
apache::mod::prefork::serverlimit: 1024
apache::mod::prefork::maxclients: 1024
apache::mod::prefork::maxrequestsperchild: 4000

candlepin::java_opts: "-Xms1024m -Xmx8192m"

postgresql::server::config_entries:
  max_connections: 1000
  shared_buffers: 32GB
  work_mem: 8MB
  effective_cache_size: 32GB
  autovacuum_vacuum_cost_limit: 2000
