---
apache::mod::prefork::serverlimit: 1024
apache::mod::prefork::maxclients: 1024
apache::mod::prefork::maxrequestsperchild: 4000

postgresql::server::config_entries:
  max_connections: 1000
  shared_buffers: 4GB
  effective_cache_size: 16GB
  autovacuum_vacuum_cost_limit: 2000
