# foreman-installer main configuration file
# note current configuration is written to foreman-installer.yaml every time foreman-install is run

## Installer configuration
# Path to answer file
:answer_file: ./config/answers.yaml
:installer_dir: .
# Uncomment if you want to load puppet modules from a specific path, $pwd/modules is used by default
:modules_dir: ./_build/modules

## Useful for development, e.g. when you want to move log files to local directory
:log_dir: '/var/log/foreman-installer'
:log_name: 'foreman-installer.log'
:log_level: :debug

# Change if you want to debug default answers for you modules, this directory holds default answers
# :default_values_dir: /tmp

## Advanced configuration - if not set it's ignored
# :log_owner: root
# :log_group: root
# :config_header_file:
# :dont_save_answers:

# If using the Debian ruby-kafo package, uncomment this
# :kafo_modules_dir: /usr/lib/ruby/vendor_ruby/kafo/modules

## Kafo tuning, customization of core functionality
:name: Foreman
# :no_prefix: false
:order:
  - foreman
  - foreman_proxy
  - puppet

# The mapping hash provides Kafo with the information to find plugin classes
:mapping:
  :foreman::plugin::bootdisk:
    :dir_name: foreman
    :manifest_name: plugin/bootdisk
  :foreman::plugin::puppetdb:
    :dir_name: foreman
    :manifest_name: plugin/puppetdb
  :foreman::plugin::hooks:
    :dir_name: foreman
    :manifest_name: plugin/hooks
  :foreman::plugin::discovery:
    :dir_name: foreman
    :manifest_name: plugin/discovery
  :foreman::plugin::chef:
    :dir_name: foreman
    :manifest_name: plugin/chef
  :foreman::plugin::templates:
    :dir_name: foreman
    :manifest_name: plugin/templates
  :foreman::plugin::setup:
    :dir_name: foreman
    :manifest_name: plugin/setup
  :foreman::plugin::default_hostgroup:
    :dir_name: foreman
    :manifest_name: plugin/default_hostgroup
  :foreman::compute::rackspace:
    :dir_name: foreman
    :manifest_name: compute/rackspace
  :foreman::compute::openstack:
    :dir_name: foreman
    :manifest_name: compute/openstack
  :foreman::compute::vmware:
    :dir_name: foreman
    :manifest_name: compute/vmware
  :foreman::compute::libvirt:
    :dir_name: foreman
    :manifest_name: compute/libvirt
  :foreman::compute::ec2:
    :dir_name: foreman
    :manifest_name: compute/ec2
  :foreman::compute::gce:
    :dir_name: foreman
    :manifest_name: compute/gce
  :foreman::compute::ovirt:
    :dir_name: foreman
    :manifest_name: compute/ovirt
